language: objective-c
script: 
- set -o pipefail
- xcodebuild $XCODE_ACTION -scheme SwiftValidators | xcpretty

xcode_project: SwiftValidators.xcodeproj
xcode_scheme: SwiftValidators
osx_image: xcode8
install: pod install --repo-update